kind: pipeline
type: docker
name: Testing Python CI/CD

environment:
  MY_SECRET:
    from_secret: MY_SECRET

steps:
- name: Black Code Format Check
  image: juliopdx/netauto
  commands:
  - black . --check

- name: Precheck OSPF and BGP
  image: juliopdx/netauto
  commands:
  - pytest test.py --disable-pytest-warnings -s

- name: Precheck Configuration Diff
  image: juliopdx/netauto
  commands:
  - python build.py

- name: Deploy Configurations
  image: juliopdx/netauto
  commands:
  - python build.py
  when:
    branch:
    - master
    - main

trigger:
  event:
    exclude:
    - pull_request