kind: pipeline
type: docker
name: Testing Python

steps:
- name: test
  image: python
  environment:
    HELLO:
      from_secret: test_secret
  commands:
  - pip install -r requirements.txt

trigger:
  branch:
    exclude:
    - main
    - master