kind: pipeline
type: docker
name: Testing Python

steps:
- name: test installs
  image: python
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  - pip3 install -r requirements.txt
  - python3 hello.py

trigger:
  branch:
    exclude:
    - main
    - master