kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
# - name: Black Code Format Check
#   image: juliopdx/netauto
#   commands:
#   - black . --check

# - name: Batfish Prechecks
#   image: juliopdx/netauto
#   commands:
#   - python test.py

# - name: Precheck Configuration Diff
#   image: juliopdx/netauto
#   environment:
#     MY_SECRET:
#       from_secret: MY_SECRET
#   commands:
#   - python build.py --dry_run

- name: Deploy Configurations
  image: juliopdx/netauto
  environment:
    MY_SECRET:
      from_secret: MY_SECRET
  commands:
  - python build.py --no_dry_run
  when:
    branch:
    - master
    - main

- name: Suzieq Check
  image: python:3.9
  privileged: true
  commands:
  # - python3 -m venv myvenv
  # - . myvenv/bin/activate
  - pip install suzieq
  - git clone https://github.com/netenglabs/suzieq.git
  - python test_suzieq.py
  volumes:
  - name: suzieq
    path: /tmp/suz

volumes:
- name: suzieq
  host:
    path: /home/juliopdx/suz

trigger:
  event:
    exclude:
    - pull_request