kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo $HELLO
  environment:
    HELLO:
      from_secret: test_secret

- name: fr
  image: alpine
  commands:
  - echo bonjour monde

trigger:
  branch:
    exclude:
    - main
    - master