kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Precheck OSPF and BGP
  image: juliopdx/netauto
  commands:
  - pytest test.py --disable-pytest-warnings -s

- name: Deploy Configurations
  image: juliopdx/netauto
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  - python build.py
  when:
    branch:
    - master
    - main
