kind: pipeline
type: docker
name: Testing Python

steps:
- name: test installs
  image: python
  environment:
    HELLO:
      from_secret: test_secret
  commands:
  - pip3 install -r requirements.txt
  - python3 hello.py

- name: test rich
  image: python
  commands:
  - python3 -m rich

trigger:
  branch:
    exclude:
    - main
    - master