kind: pipeline
type: docker
name: Testing Python CI/CD

environment:
  MY_PASS:
    from_secret: MY_PASS

steps:
- name: Install and deploy
  image: python
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  - pip3 install -r requirements.txt
  - "black ."
  - pylint hello.py
  - python3 hello.py

trigger:
  branch:
    exclude:
    - main
    - master