kind: pipeline
type: exec
name: Testing Python CI/CD

platform:
  os: linux
  arch: amd64

steps:
- name: Install dependencies and check standards
  commands:
  - pip3 install -r requirements.txt
  - "black ."
  - pylint hello.py

- name: Execute script for backup
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  - python3 hello.py

trigger:
  branch:
    exclude:
    - main
    - master