kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Test OSPF and BGP
  image: juliopdx/netauto
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
  # - pip3 install -r requirements.txt
  - pytest test.py --disable-pytest-warnings

trigger:
  branch:
    exclude:
    - main
    - master