---
pdx-rtr-eos-01:
  hostname: 192.168.10.121
  groups:
    - eos

pdx-rtr-eos-02:
  hostname: 192.168.10.122
  groups:
    - eos

pdx-rtr-eos-03:
  hostname: 192.168.10.123
  groups:
    - eos

pdx-rtr-eos-04:
  hostname: 192.168.10.124
  groups:
    - eos